# Generated by Django 3.2 on 2022-07-23 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('uuid', models.UUIDField(verbose_name=uuid.uuid4)),
                ('description', models.TextField()),
            ],
        ),
    ]
