# Generated by Django 3.2 on 2022-07-23 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
