# Generated by Django 3.2 on 2022-07-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220725_0130'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='cell_phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
