# Generated by Django 3.2 on 2022-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ns', 'no_status'), ('td', 'to_do'), ('ip', 'in_progress'), ('cp', 'complete')], max_length=2)),
            ],
        ),
    ]
